import { configuredBackupRetentionDays, configuredPrivacyContactUrl } from "@/config/publicOrigin";
import { PUBLIC_INFORMATION_EFFECTIVE_DATE, PublicInformationLayout } from "./PublicInformationLayout";

export default function PrivacyTermsPage() {
  const backupRetentionDays = configuredBackupRetentionDays();
  const privacyContactUrl = configuredPrivacyContactUrl();
  return <PublicInformationLayout eyebrow={`Version 2 · Effective ${PUBLIC_INFORMATION_EFFECTIVE_DATE}`} title="Privacy notice" introduction="How this private gear share uses your information, who can see it, and what is not part of the service.">
      <nav aria-label="Privacy sections" className="my-6 flex flex-wrap gap-3 text-sm"><a className="underline" href="#visibility">Visibility</a><a className="underline" href="#data">Data</a><a className="underline" href="#providers">Providers</a><a className="underline" href="#retention">Retention</a><a className="underline" href="#rights">Member rights</a><a className="underline" href="#excluded">Not included</a></nav>
      <div className="space-y-8 leading-relaxed">
        <section id="visibility"><h2 className="font-serif text-2xl font-bold">Who can see what</h2><p>Every member must be approved by an Administrator. Approved members can see the private catalog, gear photos, short member introductions, and the ZIP code for an item’s pickup contact. The catalog never shows street addresses, maps, exact distances, email addresses, or phone numbers.</p></section>
        <section id="data"><h2 className="font-serif text-2xl font-bold">Information we keep</h2><p>We keep the answers submitted with a membership application, the confirmed email used to sign in, profile details you choose to add, gear listings and photos, and loan history. Gear photos are resized and stored privately. After a loan is approved, only the borrower and pickup contact can see the email, phone, or notes needed to coordinate pickup and return. Those details are hidden again when the loan ends.</p></section>
        <section id="providers"><h2 className="font-serif text-2xl font-bold">Authentication and service providers</h2><p>Supabase provides account authentication and private application storage. When Google sign-in is offered, Google supplies Supabase a provider identifier, confirmed email, and basic profile information such as a name; its authentication response may also include profile-image metadata. Gear Share uses the identifier and email to establish or link the account and may use the name to help set up the member profile. It does not use the Google profile image or request access to Google Drive, contacts, calendar, photos, messages, or other Google services. Google authentication never approves membership; Administrator review remains required.</p><p className="mt-3">If an Administrator turns on AI suggestions, a member may choose to send resized listing photos and a small amount of listing information to OpenAI. Suggestions must be reviewed before saving. Amazon SES may send account, loan, and wanted-gear emails. Problems such as bounces or complaints can pause future email. An email failure never changes what happened in the gear share.</p></section>
        <section id="retention"><h2 className="font-serif text-2xl font-bold">How long information is kept</h2><p>Application answers are available for up to 90 days while an application is pending and up to 30 days after a decision. Dismissed notifications are removed after 30 days; other notifications after 365 days. Email delivery records are cleared or stripped of message details after 90 days. Encrypted backups may remain for up to {backupRetentionDays} days after deletion. Limits may apply to repeated password recovery, invitations, notifications, or AI requests to prevent abuse.</p></section>
        <section id="rights"><h2 className="font-serif text-2xl font-bold">Your choices and corrections</h2><p>You can update your profile and email choices from the Account page. Use the <a className="text-terracotta underline" href={privacyContactUrl}>public privacy contact page</a> to ask for a copy or correction of your information, help recovering your account, or a reviewed deletion request. Some loan, ownership, safety, and legally required records may need to be kept.</p></section>
        <section id="excluded" className="rounded-lg border-2 border-terracotta/60 bg-sand/60 p-4"><h2 className="font-serif text-2xl font-bold">Not included in this gear share</h2><p className="mt-2">Public profiles and public media; public community discovery or creation; cross-community features; maps, geocoding, street addresses, exact distance, or radius search; payments; informal member-to-member contact that bypasses formal loans; Administrator statistics and member-count dashboards; generated illustrations; marketing broadcasts and newsletters; and automatic membership admission.</p></section>
      </div>
  </PublicInformationLayout>;
}
